server:
  port: 8084

spring:
  application:
    name: ai-review-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-review-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ai.codereview.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ai.codereview.common.dto.ReviewRequest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

openai:
  api-key: ${GROQ_API_KEY}
  model: llama-3.3-70b-versatile
  base-url: https://api.groq.com/openai/v1

kafka:
  topics:
    review-tasks: review-tasks
    review-results: review-results

logging:
  level:
    com.ai.codereview: DEBUG
    com.aicodereview: DEBUG