apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: ai-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: ai-code-review-app-eureka-server:latest
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: ai-review-config
            - secretRef:
                name: ai-review-secrets

          ports:
            - containerPort: 8761

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
