{
 "title": "Kafka Lag",
 "tags": [ "kafka" ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Consumer Lag per Topic",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_count",
     "legendFormat": "{{topic}} - {{group}}"
    }
   ]
  },
  {
   "title": "Kafka Listener Processing Rate (msg/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(spring_kafka_listener_seconds_count[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Listener Avg Latency (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(spring_kafka_listener_seconds_sum[1m]) / rate(spring_kafka_listener_seconds_count[1m]) * 1000",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}