apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-review-config
  namespace: ai-review

data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_DATASOURCE_USERNAME: "codereview"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/codereview"
  SPRING_REDIS_HOST: "redis-service"
  WEAVIATE_HOST: "weaviate-service"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka"